-- gen-manifest.lua (host) — walk overlay/ and patches/ and emit a checksummed
-- install manifest at install/manifest.lua. The online installer reads this to
-- know which files to download (and verify) and where to place them.
-- Run from the repo root: lua5.3 tools/gen-manifest.lua
package.path = "overlay/lib/?.lua;overlay/lib/?/init.lua;" .. package.path
_G.checkArg = _G.checkArg or function() end   -- OpenOS global, stubbed on host
local hash = require("aurora.hash")

local function popen_lines(cmd)
  local out, h = {}, assert(io.popen(cmd))
  for line in h:lines() do out[#out + 1] = line end
  h:close()
  return out
end

local function readAll(path)
  local f = assert(io.open(path, "rb"))
  local d = f:read("*a"); f:close(); return d
end

local files = {}

-- overlay/<rel>  ->  /<rel>
for _, path in ipairs(popen_lines("find overlay -type f -name '*'")) do
  local rel = path:gsub("^overlay/", "")
  files[#files + 1] = {
    src = path, dst = "/" .. rel, kind = "overlay",
    sha256 = hash.sha256(readAll(path)),
  }
end

-- patches/<rel>  ->  /<rel>   (skip the *.orig pristine copies)
for _, path in ipairs(popen_lines("find patches -type f -name '*.lua' ! -name '*.orig'")) do
  local rel = path:gsub("^patches/", "")
  files[#files + 1] = {
    src = path, dst = "/" .. rel, kind = "patch",
    sha256 = hash.sha256(readAll(path)),
  }
end

table.sort(files, function(a, b) return a.dst < b.dst end)

-- read version from overlay/lib/aurora/version.lua if present, else default
local version = "1.0.0"

local out = {"-- AUTO-GENERATED by tools/gen-manifest.lua — do not edit by hand.\n"}
out[#out + 1] = "return {\n"
out[#out + 1] = string.format("  version = %q,\n", version)
out[#out + 1] = "  files = {\n"
for _, f in ipairs(files) do
  out[#out + 1] = string.format(
    "    {src=%q, dst=%q, kind=%q, sha256=%q},\n", f.src, f.dst, f.kind, f.sha256)
end
out[#out + 1] = "  },\n}\n"

local mf = assert(io.open("install/manifest.lua", "w"))
mf:write(table.concat(out)); mf:close()
print(string.format("wrote install/manifest.lua: %d files", #files))
