-- gen-apidocs.lua (host) — dogfood `adoc`: generate docs/API.md from the public
-- Aurora libraries. Run from the repo root: lua5.3 tools/gen-apidocs.lua
package.path = "overlay/lib/?.lua;overlay/lib/?/init.lua;" .. package.path
_G.checkArg = _G.checkArg or function() end
local doc = require("aurora.doc")

local function readAll(p) local f = assert(io.open(p, "rb")); local d = f:read("*a"); f:close(); return d end

-- title -> source path (the public-facing libraries)
local LIBS = {
  {"json", "overlay/lib/json.lua"},
  {"inspect", "overlay/lib/inspect.lua"},
  {"class", "overlay/lib/class.lua"},
  {"argparse", "overlay/lib/argparse.lua"},
  {"ahttp", "overlay/lib/ahttp.lua"},
  {"anet", "overlay/lib/anet.lua"},
  {"aurora.util", "overlay/lib/aurora/util.lua"},
  {"aurora.fsx", "overlay/lib/aurora/fsx.lua"},
  {"aurora.hash", "overlay/lib/aurora/hash.lua"},
  {"aurora.semver", "overlay/lib/aurora/semver.lua"},
  {"aurora.lua.parser", "overlay/lib/aurora/lua/parser.lua"},
  {"aurora.lua.gen", "overlay/lib/aurora/lua/gen.lua"},
  {"aurora.analyze", "overlay/lib/aurora/analyze.lua"},
  {"aurora.doc", "overlay/lib/aurora/doc.lua"},
}

local out = {
  "# Aurora API Reference\n",
  "_Auto-generated by `adoc` (`tools/gen-apidocs.lua`) — do not edit by hand._\n",
  "These are the libraries intended for use from your own programs via\n`require(...)`.\n",
}
for _, lib in ipairs(LIBS) do
  local title, path = lib[1], lib[2]
  out[#out + 1] = "\n---\n\n## `" .. title .. "`\n"
  local md = assert(doc.markdown(readAll(path), {publicOnly = true}))
  out[#out + 1] = md
end

local f = assert(io.open("docs/API.md", "w"))
f:write(table.concat(out, "\n")); f:close()
print("wrote docs/API.md (" .. #LIBS .. " libraries)")
