require("shim.oc")
local t = require("aurora.test")
local json = require("json")

t.describe("json.encode", function()
  t.it("encodes integers and floats", function()
    t.expect(json.encode(42)).toEqual("42")
    t.expect(json.encode(1.5)).toEqual("1.5")
  end)
  t.it("encodes booleans and null", function()
    t.expect(json.encode(true)).toEqual("true")
    t.expect(json.encode(json.null)).toEqual("null")
  end)
  t.it("escapes strings", function()
    t.expect(json.encode('a"b\n')).toEqual('"a\\"b\\n"')
  end)
  t.it("encodes arrays", function()
    t.expect(json.encode({1, 2, 3})).toEqual("[1,2,3]")
    t.expect(json.encode({})).toEqual("[]")
  end)
  t.it("encodes objects with sorted keys", function()
    t.expect(json.encode({b = 1, a = 2})).toEqual('{"a":2,"b":1}')
  end)
  t.it("forces empty object with json.object", function()
    t.expect(json.encode(json.object{})).toEqual("{}")
  end)
  t.it("pretty-prints", function()
    t.expect(json.encode({1, 2}, {pretty = true, indent = " "}))
      .toEqual("[\n 1,\n 2\n]")
  end)
  t.it("rejects non-finite numbers", function()
    t.expect(function() json.encode(1/0) end).toThrow("non-finite")
  end)
end)

t.describe("json.decode", function()
  t.it("round-trips scalars", function()
    t.expect(json.decode("42")).toEqual(42)
    t.expect(json.decode("true")).toEqual(true)
    t.expect(json.decode('"hi"')).toEqual("hi")
  end)
  t.it("decodes null to sentinel", function()
    t.expect(json.decode("null")).toBe(json.null)
  end)
  t.it("decodes arrays and objects", function()
    t.expect(json.decode("[1,2,3]")).toEqual({1, 2, 3})
    t.expect(json.decode('{"a":1,"b":[2,3]}')).toEqual({a = 1, b = {2, 3}})
  end)
  t.it("handles whitespace and unicode escapes", function()
    t.expect(json.decode('  { "k" : "\\u0041" } ')).toEqual({k = "A"})
  end)
  t.it("rejects trailing garbage", function()
    t.expect(function() json.decode("1 2") end).toThrow("trailing")
  end)
  t.it("rejects malformed input", function()
    t.expect(function() json.decode("{bad}") end).toThrow("json:")
  end)
  t.it("round-trips a complex value", function()
    local v = {name = "aurora", ver = {1, 0, 0}, deps = json.object{}, ok = true}
    t.expect(json.decode(json.encode(v))).toEqual(v)
  end)
end)

os.exit((t.run({quiet = true})))
