require("shim.oc")
local t = require("aurora.test")
local semver = require("aurora.semver")
local inspect = require("inspect")
local class = require("class")
local argparse = require("argparse")
local util = require("aurora.util")

t.describe("semver", function()
  t.it("parses and compares", function()
    t.expect(semver.compare("1.2.3", "1.2.4")).toEqual(-1)
    t.expect(semver.compare("2.0.0", "1.9.9")).toEqual(1)
    t.expect(semver.compare("1.0.0", "1.0.0")).toEqual(0)
  end)
  t.it("orders prereleases below releases", function()
    t.expect(semver.lt("1.0.0-rc1", "1.0.0")).toBeTruthy()
  end)
  t.it("matches caret constraints", function()
    t.expect(semver.satisfies("1.4.0", "^1.2.3")).toBeTruthy()
    t.expect(semver.satisfies("2.0.0", "^1.2.3")).toBeFalsy()
    t.expect(semver.satisfies("0.2.9", "^0.2.1")).toBeTruthy()
    t.expect(semver.satisfies("0.3.0", "^0.2.1")).toBeFalsy()
  end)
  t.it("matches tilde and range constraints", function()
    t.expect(semver.satisfies("1.2.9", "~1.2.3")).toBeTruthy()
    t.expect(semver.satisfies("1.3.0", "~1.2.3")).toBeFalsy()
    t.expect(semver.satisfies("1.5.0", ">=1.2.0")).toBeTruthy()
    t.expect(semver.satisfies("9.9.9", "*")).toBeTruthy()
  end)
  t.it("picks best matching version", function()
    t.expect(semver.best({"1.0.0", "1.2.0", "2.0.0"}, "^1.0.0")).toEqual("1.2.0")
  end)
end)

t.describe("inspect", function()
  t.it("renders scalars and strings", function()
    t.expect(inspect(42)).toEqual("42")
    t.expect(inspect("hi")).toEqual('"hi"')
  end)
  t.it("renders nested tables", function()
    t.expect(inspect({1, 2}, {newline = "", indent = ""})).toContain("1,")
    t.expect(inspect({a = 1})).toContain("a = 1")
  end)
  t.it("handles cycles", function()
    local x = {}; x.self = x
    t.expect(inspect(x)).toContain("<cycle>")
  end)
  t.it("quotes non-identifier keys", function()
    t.expect(inspect({["a b"] = 1})).toContain('["a b"]')
  end)
end)

t.describe("class", function()
  local Animal = class("Animal")
  function Animal:init(name) self.name = name end
  function Animal:speak() return "..." end
  local Dog = class("Dog", Animal)
  function Dog:speak() return self.name .. " woof" end

  t.it("constructs and dispatches", function()
    local d = Dog("Rex")
    t.expect(d.name).toEqual("Rex")        -- inherited init
    t.expect(d:speak()).toEqual("Rex woof")
  end)
  t.it("inherits methods", function()
    local a = Animal("Cat")
    t.expect(a:speak()).toEqual("...")
  end)
  t.it("reports instance-of across the chain", function()
    local d = Dog("Rex")
    t.expect(d:isInstanceOf(Dog)).toBeTruthy()
    t.expect(d:isInstanceOf(Animal)).toBeTruthy()
  end)
end)

t.describe("argparse", function()
  local function build()
    local p = argparse("greet", "say hi")
    p:positional("name", "who")
    p:flag("loud", "shout", {short = "l"})
    p:option("times", "count", {short = "n", default = "1"})
    return p
  end
  t.it("parses positionals, flags and options", function()
    local a = build():parse("-l", "-n", "3", "world")
    t.expect(a.name).toEqual("world")
    t.expect(a.loud).toBe(true)
    t.expect(a.times).toEqual("3")
  end)
  t.it("supports --opt=value and defaults", function()
    local a = build():parse("--times=5", "bob")
    t.expect(a.times).toEqual("5")
    local b = build():parse("ann")
    t.expect(b.times).toEqual("1")
    t.expect(b.loud).toBe(false)
  end)
  t.it("errors on missing positional", function()
    local a, err = build():parse("-l")
    t.expect(a).toBeNil()
    t.expect(err).toContain("missing")
  end)
  t.it("collects extra positionals into rest", function()
    local a = build():parse("x", "y", "z")
    t.expect(a.rest).toEqual({"y", "z"})
  end)
end)

t.describe("util", function()
  t.it("trims and splits", function()
    t.expect(util.trim("  hi  ")).toEqual("hi")
    t.expect(util.split("a,b,,c", ",", true)).toEqual({"a", "b", "", "c"})
  end)
  t.it("prefix/suffix checks", function()
    t.expect(util.startsWith("foobar", "foo")).toBeTruthy()
    t.expect(util.endsWith("foobar", "bar")).toBeTruthy()
  end)
  t.it("maps and filters", function()
    t.expect(util.map({1, 2, 3}, function(x) return x * 2 end)).toEqual({2, 4, 6})
    t.expect(util.filter({1, 2, 3, 4}, function(x) return x % 2 == 0 end)).toEqual({2, 4})
  end)
  t.it("humanizes bytes", function()
    t.expect(util.humanBytes(512)).toEqual("512B")
    t.expect(util.humanBytes(1536)).toEqual("1.5K")
  end)
end)

os.exit((t.run({quiet = true})))
