-- Verifies the shim + atest harness work on the host.
require("shim.oc")
local t = require("aurora.test")

t.describe("atest harness", function()
  t.it("equates values", function() t.expect(1 + 1).toEqual(2) end)
  t.it("deep-equates tables", function()
    t.expect({a = 1, b = {2, 3}}).toEqual({a = 1, b = {2, 3}})
  end)
  t.it("matches truthiness", function() t.expect("x").toBeTruthy() end)
  t.it("detects substrings", function() t.expect("hello").toContain("ell") end)
  t.it("catches thrown errors", function()
    t.expect(function() error("boom") end).toThrow("boom")
  end)
end)

t.describe("oc shim", function()
  t.it("provides checkArg", function()
    t.expect(function() checkArg(1, 5, "string") end).toThrow("expected")
  end)
  t.it("provides unicode.len for utf-8", function()
    t.expect(unicode.len("héllo")).toEqual(5)
  end)
  t.it("provides unicode.sub for utf-8", function()
    t.expect(unicode.sub("héllo", 1, 2)).toEqual("hé")
  end)
end)

os.exit((t.run()))
