require("shim.oc")
local t = require("aurora.test")
local anet = require("anet")
local json = require("json")

t.describe("anet wire protocol", function()
  t.it("encodes and decodes messages", function()
    local wire = anet.encode({hello = "world", n = 3})
    t.expect(wire:sub(1, 5)).toEqual("ANET1")
    t.expect(anet.decode(wire)).toEqual({hello = "world", n = 3})
  end)
  t.it("ignores foreign frames", function()
    t.expect(anet.decode("not-anet")).toBeNil()
    t.expect(anet.decode("ANET1{bad json")).toBeNil()
    t.expect(anet.decode(42)).toBeNil()
  end)
end)

t.describe("anet rpc envelopes", function()
  t.it("builds request with auto id", function()
    local r = anet.rpcRequest("add", {1, 2})
    t.expect(r.jsonrpc).toEqual("2.0")
    t.expect(r.method).toEqual("add")
    t.expect(r.params).toEqual({1, 2})
    t.expect(type(r.id)).toEqual("number")
  end)
  t.it("builds result and error", function()
    t.expect(anet.rpcResult(7, 42)).toEqual({jsonrpc = "2.0", result = 42, id = 7})
    local e = anet.rpcError(7, -32601, "nope")
    t.expect(e.error.code).toEqual(-32601)
    t.expect(e.error.message).toEqual("nope")
  end)
  t.it("survives a full json round-trip", function()
    local r = anet.rpcRequest("sum", {2, 3}, 99)
    t.expect(json.decode(json.encode(r))).toEqual(r)
  end)
end)

os.exit((t.run({quiet = true})))
