require("shim.oc")
local t = require("aurora.test")
local sandbox = require("aurora.sandbox")

t.describe("sandbox", function()
  t.it("runs safe code and returns results", function()
    local ok, r = sandbox.run("return 2 + 3 * 4")
    t.expect(ok).toBe(true)
    t.expect(r).toEqual(14)
  end)
  t.it("exposes the pure stdlib", function()
    local ok, r = sandbox.run("return string.upper('a') .. math.floor(1.9)")
    t.expect(ok).toBe(true)
    t.expect(r).toEqual("A1")
  end)
  t.it("denies io, filesystem, component and require", function()
    for _, name in ipairs({"io", "require", "load", "dofile", "loadfile",
                           "component", "computer", "_ENV.io"}) do
      local ok, v = sandbox.eval(name)
      t.expect(ok).toBe(true)       -- accessing returns nil, not an error
      t.expect(v).toBeNil()
    end
  end)
  t.it("denies dangerous os functions but allows safe ones", function()
    t.expect(select(2, sandbox.eval("os.remove"))).toBeNil()
    t.expect(select(2, sandbox.eval("os.execute"))).toBeNil()
    t.expect(select(2, sandbox.eval("type(os.time)"))).toEqual("function")
  end)
  t.it("keeps _G pointing inside the sandbox", function()
    local ok, v = sandbox.eval("_G.os.execute")
    t.expect(ok).toBe(true)
    t.expect(v).toBeNil()           -- no escape to the real _G
  end)
  t.it("catches runtime errors", function()
    local ok, err = sandbox.run("error('boom')")
    t.expect(ok).toBe(false)
    t.expect(tostring(err)).toContain("boom")
  end)
  t.it("reports compile errors", function()
    local ok, err = sandbox.run("this is not lua")
    t.expect(ok).toBe(false)
    t.expect(err).toContain("compile error")
  end)
  t.it("injects extra globals", function()
    local ok, v = sandbox.run("return answer * 2", {env = {answer = 21}})
    t.expect(ok).toBe(true)
    t.expect(v).toEqual(42)
  end)
  t.it("passes arguments to the chunk", function()
    local ok, v = sandbox.run("local a, b = ...; return a + b", {args = {3, 4}})
    t.expect(v).toEqual(7)
  end)
  t.it("aborts runaway loops via the step limit", function()
    local ok, err = sandbox.run("while true do end", {steps = 100000})
    t.expect(ok).toBe(false)
    t.expect(tostring(err)).toContain("step limit")
  end)
end)

os.exit((t.run({quiet = true})))
