require("shim.oc")
local t = require("aurora.test")
local lang = require("aurora.lang")

-- isolate: register fresh catalogs for the test
lang.register("en", {hi = "Hello", bye = "Goodbye", greet = "Hi, {name}!"})
lang.register("ru", {hi = "Привет", greet = "Привет, {name}!"})

t.describe("lang", function()
  t.it("defaults to english and looks up keys", function()
    lang.setLocale("en")
    t.expect(lang.t("hi")).toEqual("Hello")
  end)
  t.it("switches locale", function()
    lang.setLocale("ru")
    t.expect(lang.getLocale()).toEqual("ru")
    t.expect(lang.t("hi")).toEqual("Привет")
  end)
  t.it("falls back to english for missing keys", function()
    lang.setLocale("ru")           -- ru has no 'bye'
    t.expect(lang.t("bye")).toEqual("Goodbye")
  end)
  t.it("returns the key when missing everywhere", function()
    t.expect(lang.t("nonexistent.key")).toEqual("nonexistent.key")
  end)
  t.it("substitutes {named} placeholders", function()
    lang.setLocale("ru")
    t.expect(lang.t("greet", {name = "Аврора"})).toEqual("Привет, Аврора!")
    lang.setLocale("en")
    t.expect(lang.t("greet", {name = "Aurora"})).toEqual("Hi, Aurora!")
  end)
  t.it("keeps an unknown placeholder literal", function()
    t.expect(lang.t("greet", {})).toEqual("Hi, {name}!")
  end)
  t.it("lists registered locales sorted and reports availability", function()
    t.expect(lang.has("ru")).toBeTruthy()
    t.expect(lang.has("zz")).toBeFalsy()
    local locales = lang.locales()
    t.expect(locales[1]).toEqual("en")   -- sorted
  end)
end)

t.describe("lang catalog files", function()
  t.it("loads a catalog from a file path", function()
    local p = "/tmp/aurora_locale_test.lua"
    require("aurora.fsx").writeAll(p, 'return {custom = "loaded!"}')
    t.expect(lang.load("xx", p)).toBeTruthy()
    lang.setLocale("xx")
    t.expect(lang.t("custom")).toEqual("loaded!")
    lang.setLocale("en")
    os.remove(p)
  end)
end)

os.exit((t.run({quiet = true})))
