require("shim.oc")
local t = require("aurora.test")
local parser = require("aurora.lua.parser")
local analyze = require("aurora.analyze")

t.describe("parser", function()
  t.it("parses local declarations", function()
    local ast = parser.parse("local a, b = 1, 2")
    local s = ast.stmts[1]
    t.expect(s.tag).toEqual("Local")
    t.expect(s.names).toEqual({"a", "b"})
    t.expect(#s.exprs).toEqual(2)
  end)
  t.it("respects operator precedence", function()
    -- 1 + 2 * 3  ==  1 + (2 * 3)
    local ast = parser.parse("return 1 + 2 * 3")
    local e = ast.stmts[1].exprs[1]
    t.expect(e.tag).toEqual("Binop")
    t.expect(e.op).toEqual("+")
    t.expect(e.rhs.tag).toEqual("Binop")
    t.expect(e.rhs.op).toEqual("*")
  end)
  t.it("parses ^ as right-associative", function()
    local ast = parser.parse("return 2 ^ 3 ^ 4")
    local e = ast.stmts[1].exprs[1]
    t.expect(e.op).toEqual("^")
    t.expect(e.rhs.tag).toEqual("Binop")   -- 3 ^ 4 grouped on the right
  end)
  t.it("parses calls, indexes and method calls", function()
    local ast = parser.parse("a.b[1]:m(x)")
    local s = ast.stmts[1]
    t.expect(s.tag).toEqual("CallStat")
    t.expect(s.call.tag).toEqual("MethodCall")
    t.expect(s.call.method).toEqual("m")
  end)
  t.it("parses control flow and functions", function()
    local ast = parser.parse([[
local function f(a, ...)
  for i = 1, a do
    if i > 2 then return i end
  end
end]])
    t.expect(ast.stmts[1].tag).toEqual("LocalFunction")
    t.expect(ast.stmts[1].func.vararg).toBe(true)
  end)
  t.it("returns nil + error on malformed input", function()
    local ast, err = parser.parse("local = 5")
    t.expect(ast).toBeNil()
    t.expect(err).toContain("parse:")
  end)
end)

t.describe("analyze", function()
  t.it("flags reads of undefined names", function()
    local f = analyze.check("return foo")
    t.expect(#f).toEqual(1)
    t.expect(f[1].message).toContain("undefined name 'foo'")
  end)
  t.it("does not flag locals, builtins or file-globals", function()
    t.expect(analyze.check("local x = 1\nreturn x")).toEqual({})
    t.expect(analyze.check("return print(math.floor(1.5))")).toEqual({})
    -- forward-referenced global function is fine
    t.expect(analyze.check("function a() end\nreturn a()")).toEqual({})
  end)
  t.it("flags unused locals (but not _ or params)", function()
    local f = analyze.check("local x = 1\nreturn 2")
    t.expect(#f).toEqual(1)
    t.expect(f[1].message).toContain("unused local 'x'")
    t.expect(analyze.check("local _ = 1\nreturn 2")).toEqual({})
  end)
  t.it("respects nested scopes", function()
    -- inner x is unused; outer x is used by the return
    local f = analyze.check("local x = 1\ndo local x = 2 end\nreturn x")
    t.expect(#f).toEqual(1)
    t.expect(f[1].message).toContain("unused local 'x'")
    t.expect(f[1].line).toEqual(2)
  end)
  t.it("reports parse errors as errors", function()
    local f = analyze.check("local = 5")
    t.expect(f[1].severity).toEqual("error")
  end)
  t.it("understands assignment targets vs reads", function()
    -- t is a known-undefined read here (used before any binding)
    local f = analyze.check("local t = {}\nt.k = 1\nreturn t")
    t.expect(f).toEqual({})
  end)
end)

os.exit((t.run({quiet = true})))
